In [1]:
import pandas as pd

In [2]:
import os

print(os.getcwd())

c:\Users\ushab\ecommerce_data_analysis\notebook

In [3]:
print(os.listdir())

['01_data_understanding.ipynb']

In [4]:
import os

print(os.path.exists("../data/olist_orders_dataset.csv"))

True

In [5]:
import pandas as pd

orders = pd.read_csv("../data/olist_orders_dataset.csv")

orders.head()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15 00:00:00
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26 00:00:00

In [6]:
type(orders)

pandas.DataFrame

In [7]:
orders.shape

(99441, 8)

In [8]:
orders.columns

Index(['order_id', 'customer_id', 'order_status', 'order_purchase_timestamp',
       'order_approved_at', 'order_delivered_carrier_date',
       'order_delivered_customer_date', 'order_estimated_delivery_date'],
      dtype='str')

In [9]:
orders.info()

<class 'pandas.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 8 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   order_id                       99441 non-null  str
 1   customer_id                    99441 non-null  str
 2   order_status                   99441 non-null  str
 3   order_purchase_timestamp       99441 non-null  str
 4   order_approved_at              99281 non-null  str
 5   order_delivered_carrier_date   97658 non-null  str
 6   order_delivered_customer_date  96476 non-null  str
 7   order_estimated_delivery_date  99441 non-null  str
dtypes: str(8)
memory usage: 6.1 MB

In [10]:
orders.isnull().sum()

order_id                            0
customer_id                         0
order_status                        0
order_purchase_timestamp            0
order_approved_at                 160
order_delivered_carrier_date     1783
order_delivered_customer_date    2965
order_estimated_delivery_date       0
dtype: int64

In [11]:
orders["order_id"].nunique()

99441

In [12]:
len(orders)

99441

In [13]:
orders["order_id"].duplicated().sum()

np.int64(0)

In [14]:
customers = pd.read_csv("../data/olist_customers_dataset.csv")

In [15]:
customers.head()

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
0,06b8999e2fba1a1fbc88172c00ba8bc7,861eff4711a542e4b93843c6dd7febb0,14409,franca,SP
1,18955e83d337fd6b2def6b18a428ac77,290c77bc529b7ac935b93aa66c333dc3,9790,sao bernardo do campo,SP
2,4e7b3e00288586ebd08712fdd0374a03,060e732b5b29e8181a18229c7b0b2b5e,1151,sao paulo,SP
3,b2b6027bc5c5109e529d4dc6358b12c3,259dac757896d24d7702b9acbbff3f3c,8775,mogi das cruzes,SP
4,4f2d8ab171c80ec8364f7c12e35b23ad,345ecd01c38d18a9036ed96c73b8d066,13056,campinas,SP

In [16]:
customers.shape

(99441, 5)

In [17]:
customers.columns

Index(['customer_id', 'customer_unique_id', 'customer_zip_code_prefix',
       'customer_city', 'customer_state'],
      dtype='str')

In [18]:
customers.isnull().sum()

customer_id                 0
customer_unique_id          0
customer_zip_code_prefix    0
customer_city               0
customer_state              0
dtype: int64

In [19]:
customers['customer_id'].nunique()

99441

In [20]:
customers['customer_unique_id'].nunique()

96096

In [21]:
len(customers)

99441

In [22]:
customers["customer_id"].duplicated().sum()

np.int64(0)

In [23]:
customers['customer_unique_id'].value_counts().head(10)

customer_unique_id
8d50f5eadf50201ccdcedfb9e2ac8455    17
3e43e6105506432c953e165fb2acf44c     9
1b6c7548a2a1f9037c1fd3ddfed95f33     7
6469f99c1f9dfae7733b25662e7f1782     7
ca77025e7201e3b30c44b472ff346268     7
47c1a3033b8b77b3ab6e109eb4d5fdf3     6
dc813062e0fc23409cd255f7f53c7074     6
63cfc61cee11cbe306bff5857d00bfe4     6
f0e310a6839dce9de1638e0fe5ab282a     6
de34b16117594161a6a89c50b289d35a     6
Name: count, dtype: int64

In [24]:
customers['customer_unique_id'].duplicated().sum()

np.int64(3345)

In [25]:
len(orders)

99441

In [26]:
orders['customer_id'].nunique()

99441

In [27]:
order_items = pd.read_csv("../data/olist_order_items_dataset.csv")

In [28]:
order_items.head(10)

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:35,58.90,13.29
1,00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,2017-05-03 11:05:13,239.90,19.93
2,000229ec398224ef6ca0657da4fc703e,1,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,2018-01-18 14:48:30,199.00,17.87
3,00024acbcdf0a6daa1e931b038114c75,1,7634da152a4610f1595efa32f14722fc,9d7a1d34a5052409006425275ba1c2b4,2018-08-15 10:10:18,12.99,12.79
4,00042b26cf59d7ce69dfabb4e55b4fd9,1,ac6c3623068f30de03045865e4e10089,df560393f3a51e74553ab94004ba5c87,2017-02-13 13:57:51,199.90,18.14
5,00048cc3ae777c65dbb7d2a0634bc1ea,1,ef92defde845ab8450f9d70c526ef70f,6426d21aca402a131fc0a5d0960a3c90,2017-05-23 03:55:27,21.90,12.69
6,00054e8431b9d7675808bcb819fb4a32,1,8d4f2bb7e93e6710a28f34fa83ee7d28,7040e82f899a04d1b434b795a43b4617,2017-12-14 12:10:31,19.90,11.85
7,000576fe39319847cbb9d288c5617fa6,1,557d850972a7d6f792fd18ae1400d9b6,5996cddab893a4652a15592fb58ab8db,2018-07-10 12:30:45,810.00,70.75
8,0005a1a1728c9d785b8e2b08b904576c,1,310ae3c140ff94b03219ad0adc3c778f,a416b6a846a11724393025641d4edd5e,2018-03-26 18:31:29,145.95,11.65
9,0005f50442cb953dcd1d21e1fb923495,1,4535b0e1091c278dfd193e5a1d63b39f,ba143b05f0110f0dc71ad71b4466ce92,2018-07-06 14:10:56,53.99,11.40

In [29]:
order_items.shape

(112650, 7)

In [30]:
order_items.columns

Index(['order_id', 'order_item_id', 'product_id', 'seller_id',
       'shipping_limit_date', 'price', 'freight_value'],
      dtype='str')

In [31]:
order_items.info()

<class 'pandas.DataFrame'>
RangeIndex: 112650 entries, 0 to 112649
Data columns (total 7 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   order_id             112650 non-null  str
 1   order_item_id        112650 non-null  int64
 2   product_id           112650 non-null  str
 3   seller_id            112650 non-null  str
 4   shipping_limit_date  112650 non-null  str
 5   price                112650 non-null  float64
 6   freight_value        112650 non-null  float64
dtypes: float64(2), int64(1), str(4)
memory usage: 6.0 MB

In [32]:
order_items['order_id'].nunique()

98666

In [33]:
order_items['order_id'].value_counts().head(10)

order_id
8272b63d03f5f79c56e9e4120aec44ef    21
1b15974a0141d54e36626dca3fdc731a    20
ab14fdcfbe524636d65ee38360e22ce8    20
428a2f660dc84138d969ccd69a0ab6d5    15
9ef13efd6949e4573a18964dd1bbe7f5    15
73c8ab38f07dc94389065f7eba4f297a    14
9bdc4d4c71aa1de4606060929dee888c    14
37ee401157a3a0b28c9c6d0ed8c3b24b    13
2c2a19b5703863c908512d135aa6accc    12
3a213fcdfe7d98be74ea0dc05a8b31ae    12
Name: count, dtype: int64

In [34]:
products = pd.read_csv("../data/olist_products_dataset.csv")

In [35]:
products.head()

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
0,1e9e8ef04dbcff4541ed26657ea517e5,perfumaria,40.0,287.0,1.0,225.0,16.0,10.0,14.0
1,3aa071139cb16b67ca9e5dea641aaa2f,artes,44.0,276.0,1.0,1000.0,30.0,18.0,20.0
2,96bd76ec8810374ed1b65e291975717f,esporte_lazer,46.0,250.0,1.0,154.0,18.0,9.0,15.0
3,cef67bcfe19066a932b7673e239eb23d,bebes,27.0,261.0,1.0,371.0,26.0,4.0,26.0
4,9dc1a7de274444849c219cff195d0b71,utilidades_domesticas,37.0,402.0,4.0,625.0,20.0,17.0,13.0

In [36]:
products.columns

Index(['product_id', 'product_category_name', 'product_name_lenght',
       'product_description_lenght', 'product_photos_qty', 'product_weight_g',
       'product_length_cm', 'product_height_cm', 'product_width_cm'],
      dtype='str')

In [37]:
products.info()

<class 'pandas.DataFrame'>
RangeIndex: 32951 entries, 0 to 32950
Data columns (total 9 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   product_id                  32951 non-null  str
 1   product_category_name       32341 non-null  str
 2   product_name_lenght         32341 non-null  float64
 3   product_description_lenght  32341 non-null  float64
 4   product_photos_qty          32341 non-null  float64
 5   product_weight_g            32949 non-null  float64
 6   product_length_cm           32949 non-null  float64
 7   product_height_cm           32949 non-null  float64
 8   product_width_cm            32949 non-null  float64
dtypes: float64(7), str(2)
memory usage: 2.3 MB

In [38]:
products['product_id'].nunique()

32951

In [39]:
len(products)

32951

In [40]:
products.isnull().sum()

product_id                      0
product_category_name         610
product_name_lenght           610
product_description_lenght    610
product_photos_qty            610
product_weight_g                2
product_length_cm               2
product_height_cm               2
product_width_cm                2
dtype: int64

In [41]:
products.duplicated().sum()

np.int64(0)

In [42]:
sellers = pd.read_csv("../data/olist_sellers_dataset.csv")

In [43]:
sellers.head()

,seller_id,seller_zip_code_prefix,seller_city,seller_state
0,3442f8959a84dea7ee197c632cb2df15,13023,campinas,SP
1,d1b65fc7debc3361ea86b5f14c68d2e2,13844,mogi guacu,SP
2,ce3ad9de960102d0677a81f5d0bb7b2d,20031,rio de janeiro,RJ
3,c0f3eea2e14555b6faeea3dd58c1b1c3,4195,sao paulo,SP
4,51a04a8a6bdcb23deccc82b0b80742cf,12914,braganca paulista,SP

In [44]:
sellers.shape

(3095, 4)

In [45]:
len(sellers)

3095

In [46]:
sellers["seller_id"].nunique()

3095

In [47]:
payments = pd.read_csv("../data/olist_order_payments_dataset.csv")

In [48]:
payments.head()

,order_id,payment_sequential,payment_type,payment_installments,payment_value
0,b81ef226f3fe1789b1e8b2acac839d17,1,credit_card,8,99.33
1,a9810da82917af2d9aefd1278f1dcfa0,1,credit_card,1,24.39
2,25e8ea4e93396b6fa0d3dd708e76c1bd,1,credit_card,1,65.71
3,ba78997921bbcdc1373bb41e913ab953,1,credit_card,8,107.78
4,42fdf880ba16b47b59251dd489d4441a,1,credit_card,2,128.45

In [49]:
len(payments)

103886

In [50]:
payments['order_id'].nunique()

99440

In [51]:
payments['order_id'].value_counts().head()

order_id
fa65dad1b0e818e3ccc5cb0e39231352    29
ccf804e764ed5650cd8759557269dc13    26
285c2e15bebd4ac83635ccc563dc71f4    22
895ab968e7bb0d5659d16cd74cd1650c    21
ee9ca989fc93ba09a6eddc250ce01742    19
Name: count, dtype: int64

In [52]:
reviews = pd.read_csv("../data/olist_order_reviews_dataset.csv")

In [53]:
reviews.isnull().sum()

review_id                      0
order_id                       0
review_score                   0
review_comment_title       87656
review_comment_message     58247
review_creation_date           0
review_answer_timestamp        0
dtype: int64

In [54]:
reviews['review_id'].duplicated().sum()

np.int64(814)

In [55]:
len(reviews)

99224

In [56]:
reviews['review_id'].nunique()

98410

In [57]:
reviews['review_id'].value_counts()

review_id
c444278834184f72b1484dfe47de7f97    3
308316408775d1600dad81bd3184556d    3
2d6ac45f859465b5c185274a1c929637    3
3415c9f764e478409e8e0660ae816dd2    3
4219a80ab469e3fc9901437b73da3f75    3
                                   ..
574ed12dd733e5fa530cfd4bbf39d7c9    1
f3897127253a9592a73be9bdfdf4ed7a    1
b3de70c89b1510c4cd3d0649fd302472    1
1adeb9d84d72fe4e337617733eb85149    1
efe49f1d6f951dd88b51e6ccd4cc548f    1
Name: count, Length: 98410, dtype: int64

In [58]:
reviews['review_score'].value_counts().sort_index()

review_score
1    11424
2     3151
3     8179
4    19142
5    57328
Name: count, dtype: int64

In [59]:
category_translation = pd.read_csv(
    "../data/product_category_name_translation.csv"
)

In [60]:
category_translation.head()

    product_category_name product_category_name_english
0            beleza_saude                 health_beauty
1  informatica_acessorios         computers_accessories
2              automotivo                          auto
3         cama_mesa_banho                bed_bath_table
4        moveis_decoracao               furniture_decor

In [61]:
category_translation.isnull().sum()

product_category_name            0
product_category_name_english    0
dtype: int64

In [62]:
category_translation['product_category_name'].nunique()

71

In [63]:
len(category_translation)

71

In [64]:
geolocation = pd.read_csv(
    "../data/olist_geolocation_dataset.csv"
)

In [65]:
geolocation.head()

,geolocation_zip_code_prefix,geolocation_lat,geolocation_lng,geolocation_city,geolocation_state
0,1037,-23.545621,-46.639292,sao paulo,SP
1,1046,-23.546081,-46.644820,sao paulo,SP
2,1046,-23.546129,-46.642951,sao paulo,SP
3,1041,-23.544392,-46.639499,sao paulo,SP
4,1035,-23.541578,-46.641607,sao paulo,SP

In [66]:
geolocation.shape

(1000163, 5)

In [67]:
geolocation.isnull().sum()

geolocation_zip_code_prefix    0
geolocation_lat                0
geolocation_lng                0
geolocation_city               0
geolocation_state              0
dtype: int64

In [68]:
geolocation.duplicated().sum()

np.int64(261831)

In [69]:
orders.isnull().sum()

order_id                            0
customer_id                         0
order_status                        0
order_purchase_timestamp            0
order_approved_at                 160
order_delivered_carrier_date     1783
order_delivered_customer_date    2965
order_estimated_delivery_date       0
dtype: int64

In [70]:
orders.isnull().mean() * 100

order_id                         0.000000
customer_id                      0.000000
order_status                     0.000000
order_purchase_timestamp         0.000000
order_approved_at                0.160899
order_delivered_carrier_date     1.793023
order_delivered_customer_date    2.981668
order_estimated_delivery_date    0.000000
dtype: float64

In [71]:
orders['order_status'].value_counts()

order_status
delivered      96478
shipped         1107
canceled         625
unavailable      609
invoiced         314
processing       301
created            5
approved           2
Name: count, dtype: int64

In [72]:
orders.groupby('order_status')['order_delivered_customer_date'].apply(lambda x: x.isnull().sum() )

order_status
approved          2
canceled        619
created           5
delivered         8
invoiced        314
processing      301
shipped        1107
unavailable     609
Name: order_delivered_customer_date, dtype: int64

In [73]:
orders.dtypes

order_id                         str
customer_id                      str
order_status                     str
order_purchase_timestamp         str
order_approved_at                str
order_delivered_carrier_date     str
order_delivered_customer_date    str
order_estimated_delivery_date    str
dtype: object

In [74]:
date_cols = [
    "order_purchase_timestamp",
    "order_approved_at",
    "order_delivered_carrier_date",
    "order_delivered_customer_date",
    "order_estimated_delivery_date"
]

In [75]:
orders[date_cols] = orders[date_cols].apply(pd.to_datetime)

In [76]:
orders.dtypes

order_id                                    str
customer_id                                 str
order_status                                str
order_purchase_timestamp         datetime64[us]
order_approved_at                datetime64[us]
order_delivered_carrier_date     datetime64[us]
order_delivered_customer_date    datetime64[us]
order_estimated_delivery_date    datetime64[us]
dtype: object

In [77]:
print("length ", len(orders))
print("unique", orders['order_id'].nunique())
print("duplicate", orders.duplicated().sum())

length  99441
unique 99441
duplicate 0

In [78]:
orders['order_status'].value_counts()

order_status
delivered      96478
shipped         1107
canceled         625
unavailable      609
invoiced         314
processing       301
created            5
approved           2
Name: count, dtype: int64

In [79]:
orders[
    (orders['order_status'] == 'delivered') &
    (orders['order_delivered_customer_date'].isnull())
]

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
3002,2d1e2d5bf4dc7227b3bfebb81328c15f,ec05a6d8558c6455f0cbbd8a420ad34f,delivered,2017-11-28 17:44:07,2017-11-28 17:56:40,2017-11-30 18:12:23,NaT,2017-12-18
20618,f5dd62b788049ad9fc0526e3ad11a097,5e89028e024b381dc84a13a3570decb4,delivered,2018-06-20 06:58:43,2018-06-20 07:19:05,2018-06-25 08:05:00,NaT,2018-07-16
43834,2ebdfc4f15f23b91474edf87475f108e,29f0540231702fda0cfdee0a310f11aa,delivered,2018-07-01 17:05:11,2018-07-01 17:15:12,2018-07-03 13:57:00,NaT,2018-07-30
79263,e69f75a717d64fc5ecdfae42b2e8e086,cfda40ca8dd0a5d486a9635b611b398a,delivered,2018-07-01 22:05:55,2018-07-01 22:15:14,2018-07-03 13:57:00,NaT,2018-07-30
82868,0d3268bad9b086af767785e3f0fc0133,4f1d63d35fb7c8999853b2699f5c7649,delivered,2018-07-01 21:14:02,2018-07-01 21:29:54,2018-07-03 09:28:00,NaT,2018-07-24
92643,2d858f451373b04fb5c984a1cc2defaf,e08caf668d499a6d643dafd7c5cc498a,delivered,2017-05-25 23:22:43,2017-05-25 23:30:16,NaT,NaT,2017-06-23
97647,ab7c89dc1bf4a1ead9d6ec1ec8968a84,dd1b84a7286eb4524d52af4256c0ba24,delivered,2018-06-08 12:09:39,2018-06-08 12:36:39,2018-06-12 14:10:00,NaT,2018-06-26
98038,20edc82cf5400ce95e1afacc25798b31,28c37425f1127d887d7337f284080a0f,delivered,2018-06-27 16:09:12,2018-06-27 16:29:30,2018-07-03 19:26:00,NaT,2018-07-19

In [80]:
customers.isnull().sum()

customer_id                 0
customer_unique_id          0
customer_zip_code_prefix    0
customer_city               0
customer_state              0
dtype: int64

In [81]:
products.isnull().sum()

product_id                      0
product_category_name         610
product_name_lenght           610
product_description_lenght    610
product_photos_qty            610
product_weight_g                2
product_length_cm               2
product_height_cm               2
product_width_cm                2
dtype: int64

In [82]:
order_items.isnull().sum()

order_id               0
order_item_id          0
product_id             0
seller_id              0
shipping_limit_date    0
price                  0
freight_value          0
dtype: int64

In [83]:
products[products['product_category_name'].isnull()].head()

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
105,a41e356c76fab66334f36de622ecbd3a,NaN,NaN,NaN,NaN,650.0,17.0,14.0,12.0
128,d8dee61c2034d6d075997acef1870e9b,NaN,NaN,NaN,NaN,300.0,16.0,7.0,20.0
145,56139431d72cd51f19eb9f7dae4d1617,NaN,NaN,NaN,NaN,200.0,20.0,20.0,20.0
154,46b48281eb6d663ced748f324108c733,NaN,NaN,NaN,NaN,18500.0,41.0,30.0,41.0
197,5fb61f482620cb672f5e586bb132eae9,NaN,NaN,NaN,NaN,300.0,35.0,7.0,12.0

In [84]:
products['product_category_name']

0                               perfumaria
1                                    artes
2                            esporte_lazer
3                                    bebes
4                    utilidades_domesticas
                       ...
32946                     moveis_decoracao
32947    construcao_ferramentas_iluminacao
32948                      cama_mesa_banho
32949               informatica_acessorios
32950                      cama_mesa_banho
Name: product_category_name, Length: 32951, dtype: str

In [85]:
products[products['product_category_name'].isnull()].shape

(610, 9)

In [86]:
missing_category_products = products.loc[
    products["product_category_name"].isnull(),
    "product_id"
]

order_items["product_id"].isin(missing_category_products).sum()

np.int64(1603)

In [87]:
products[
    products['product_weight_g'].isnull() |
    products['product_height_cm'].isnull() |
    products['product_length_cm'].isnull() |
    products['product_width_cm'].isnull()
]

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
8578,09ff539a621711667c43eba6a3bd8466,bebes,60.0,865.0,3.0,NaN,NaN,NaN,NaN
18851,5eb564652db742ff8f28759cd8d2652a,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [88]:
products_with_missing_dimensions = products.loc[
    products["product_weight_g"].isnull() |
    products["product_length_cm"].isnull() |
    products["product_height_cm"].isnull() |
    products["product_width_cm"].isnull(),
    "product_id"
]

order_items["product_id"].isin(products_with_missing_dimensions).sum()

np.int64(18)

In [89]:
payments.isnull().sum()

order_id                0
payment_sequential      0
payment_type            0
payment_installments    0
payment_value           0
dtype: int64

In [90]:
reviews.isnull().sum()

review_id                      0
order_id                       0
review_score                   0
review_comment_title       87656
review_comment_message     58247
review_creation_date           0
review_answer_timestamp        0
dtype: int64

In [91]:
sellers.isnull().sum()

seller_id                 0
seller_zip_code_prefix    0
seller_city               0
seller_state              0
dtype: int64

In [92]:
category_translation.isnull().sum()

product_category_name            0
product_category_name_english    0
dtype: int64

In [93]:
geolocation.isnull().sum()

geolocation_zip_code_prefix    0
geolocation_lat                0
geolocation_lng                0
geolocation_city               0
geolocation_state              0
dtype: int64

In [94]:
orders['customer_id'].isin(customers['customer_id']).eq(False).sum()

np.int64(0)

In [95]:
order_items['order_id'].isin(orders['order_id']).eq(False).sum()

np.int64(0)

In [96]:
order_items['product_id'].isin(products['product_id']).eq(False).sum()

np.int64(0)

In [97]:
order_items['seller_id'].isin(sellers['seller_id']).eq(False).sum()

np.int64(0)

In [98]:
payments["order_id"].isin(orders["order_id"]).eq(False).sum()

np.int64(0)

In [99]:
reviews['order_id'].isin(orders['order_id']).eq(False).sum()

np.int64(0)

In [100]:
products['product_id'].duplicated().sum()

np.int64(0)

In [101]:
sellers['seller_id'].duplicated().sum()

np.int64(0)

In [102]:
customers['customer_id'].duplicated().sum()

np.int64(0)

In [103]:
customers['customer_unique_id'].nunique()

96096

In [104]:
customers['customer_unique_id'].duplicated(keep=False).sum()

np.int64(6342)

In [105]:
customer_id_counts = customers['customer_unique_id'].value_counts()

customer_id_counts[customer_id_counts > 1].shape[0]

2997

In [106]:
reviews['order_id'].duplicated().sum()

np.int64(551)

In [107]:
review_count = reviews.groupby('order_id').size()
(review_count >1).sum()

np.int64(547)

In [108]:
payments['order_id'].duplicated().sum()

np.int64(4446)

In [109]:
payment_counts = payments.groupby('order_id').size()

In [110]:
(payment_counts > 1).sum()

np.int64(2961)

In [111]:
item_counts = order_items.groupby('order_id').size()

In [112]:
(item_counts > 1).sum()

np.int64(9803)

In [113]:
order_items.dtypes

order_id                   str
order_item_id            int64
product_id                 str
seller_id                  str
shipping_limit_date        str
price                  float64
freight_value          float64
dtype: object

In [114]:
order_items['shipping_limit_date'] = pd.to_datetime(order_items['shipping_limit_date'])

In [115]:
order_items.dtypes

order_id                          str
order_item_id                   int64
product_id                        str
seller_id                         str
shipping_limit_date    datetime64[us]
price                         float64
freight_value                 float64
dtype: object

In [116]:
payments.dtypes

order_id                    str
payment_sequential        int64
payment_type                str
payment_installments      int64
payment_value           float64
dtype: object

In [117]:
reviews.dtypes

review_id                    str
order_id                     str
review_score               int64
review_comment_title         str
review_comment_message       str
review_creation_date         str
review_answer_timestamp      str
dtype: object

In [118]:
reviews['review_creation_date'] = pd.to_datetime(reviews['review_creation_date'])

In [119]:
reviews['review_answer_timestamp'] = pd.to_datetime(reviews['review_answer_timestamp'])

In [120]:
reviews[['review_creation_date', 'review_answer_timestamp']].dtypes

review_creation_date       datetime64[us]
review_answer_timestamp    datetime64[us]
dtype: object

In [121]:
products.dtypes

product_id                        str
product_category_name             str
product_name_lenght           float64
product_description_lenght    float64
product_photos_qty            float64
product_weight_g              float64
product_length_cm             float64
product_height_cm             float64
product_width_cm              float64
dtype: object

In [122]:
customers.dtypes

customer_id                   str
customer_unique_id            str
customer_zip_code_prefix    int64
customer_city                 str
customer_state                str
dtype: object

In [123]:
sellers.dtypes

seller_id                   str
seller_zip_code_prefix    int64
seller_city                 str
seller_state                str
dtype: object

In [124]:
category_translation.dtypes

product_category_name            str
product_category_name_english    str
dtype: object

In [125]:
reviews['review_score'].value_counts().sort_index()

review_score
1    11424
2     3151
3     8179
4    19142
5    57328
Name: count, dtype: int64

In [126]:
payments['payment_type'].value_counts()

payment_type
credit_card    76795
boleto         19784
voucher         5775
debit_card      1529
not_defined        3
Name: count, dtype: int64

In [127]:
payments['payment_installments'].describe()

count    103886.000000
mean          2.853349
std           2.687051
min           0.000000
25%           1.000000
50%           1.000000
75%           4.000000
max          24.000000
Name: payment_installments, dtype: float64

In [128]:
payments[payments['payment_installments'] == 0]

,order_id,payment_sequential,payment_type,payment_installments,payment_value
46982,744bade1fcf9ff3f31d860ace076d422,2,credit_card,0,58.69
79014,1a57108394169c0b47d8f876acc9ba2d,2,credit_card,0,129.94

In [129]:
payments['payment_value'].describe()

count    103886.000000
mean        154.100380
std         217.494064
min           0.000000
25%          56.790000
50%         100.000000
75%         171.837500
max       13664.080000
Name: payment_value, dtype: float64

In [130]:
payments[payments['payment_value'] == 0]

,order_id,payment_sequential,payment_type,payment_installments,payment_value
19922,8bcbe01d44d147f901cd3192671144db,4,voucher,1,0.0
36822,fa65dad1b0e818e3ccc5cb0e39231352,14,voucher,1,0.0
43744,6ccb433e00daae1283ccc956189c82ae,4,voucher,1,0.0
51280,4637ca194b6387e2d538dc89b124b0ee,1,not_defined,1,0.0
57411,00b1cb0320190ca0daa2c88b35206009,1,not_defined,1,0.0
62674,45ed6e85398a87c253db47c2d9f48216,3,voucher,1,0.0
77885,fa65dad1b0e818e3ccc5cb0e39231352,13,voucher,1,0.0
94427,c8c528189310eaa44a745b8d9d26908b,1,not_defined,1,0.0
100766,b23878b3e8eb4d25a158f57d96331b18,4,voucher,1,0.0

In [131]:
(products['product_height_cm'] < 0).sum()

np.int64(0)

In [132]:
(products['product_length_cm']< 0).sum()

np.int64(0)

In [133]:
(products['product_width_cm'] < 0).sum()

np.int64(0)

In [134]:
(products['product_photos_qty'] < 0).sum()

np.int64(0)

In [135]:
products['product_category_name'].value_counts().head(10)

product_category_name
cama_mesa_banho           3029
esporte_lazer             2867
moveis_decoracao          2657
beleza_saude              2444
utilidades_domesticas     2335
automotivo                1900
informatica_acessorios    1639
brinquedos                1411
relogios_presentes        1329
telefonia                 1134
Name: count, dtype: int64

In [136]:
(products['product_category_name'].str.strip() == "").sum()

np.int64(0)

In [137]:
valid_categories = products.loc[
    products['product_category_name'].notna(),
    "product_category_name"
]

In [138]:
valid_categories.isin(category_translation['product_category_name']).eq(False).sum()

np.int64(13)

In [139]:
unmatched_categories = valid_categories[
    valid_categories.isin(category_translation['product_category_name']).eq(False)
]

In [140]:
unmatched_categories.unique()

<StringArray>
['pc_gamer', 'portateis_cozinha_e_preparadores_de_alimentos']
Length: 2, dtype: str

In [141]:
unmatched_categories.value_counts()

product_category_name
portateis_cozinha_e_preparadores_de_alimentos    10
pc_gamer                                          3
Name: count, dtype: int64

In [142]:
(customers['customer_zip_code_prefix'] < 0).sum()

np.int64(0)

In [143]:
customers['customer_state'].nunique()

27

In [144]:
customers['customer_state'].unique()

<StringArray>
['SP', 'SC', 'MG', 'PR', 'RJ', 'RS', 'PA', 'GO', 'ES', 'BA', 'MA', 'MS', 'CE',
 'DF', 'RN', 'PE', 'MT', 'AM', 'AP', 'AL', 'RO', 'PB', 'TO', 'PI', 'AC', 'SE',
 'RR']
Length: 27, dtype: str

In [145]:
customers['customer_city'].nunique()

4119

In [146]:
customers['customer_city'].value_counts().head(10)

customer_city
sao paulo                15540
rio de janeiro            6882
belo horizonte            2773
brasilia                  2131
curitiba                  1521
campinas                  1444
porto alegre              1379
salvador                  1245
guarulhos                 1189
sao bernardo do campo      938
Name: count, dtype: int64

In [147]:
(customers['customer_city'].str.strip() ==0 ).sum()

np.int64(0)

In [148]:
(customers['customer_state'].str.strip() == 0).sum()

np.int64(0)

In [149]:
customers['customer_zip_code_prefix'].astype(str).str.len().value_counts()

customer_zip_code_prefix
5    75446
4    23995
Name: count, dtype: int64

In [150]:
(customers['customer_zip_code_prefix'] < 10000).sum()

np.int64(23995)

In [151]:
customer_id_counts = customers['customer_unique_id'].value_counts()

(customer_id_counts > 1).sum()

np.int64(2997)

In [152]:
orders_per_customer = orders.groupby('customer_id').size()

orders_per_customer.head()

customer_id
00012a2ce6f8dcda20d059ce98491703    1
000161a058600d5901f007fab4c27140    1
0001fd6190edaaf884bcaf3d49edf079    1
0002414f95344307404f0ace7a26f1d5    1
000379cdec625522490c315e70c7a9fb    1
dtype: int64

In [153]:
orders_with_customers = orders.merge(customers[['customer_id', 'customer_unique_id']], on='customer_id',
                                     how='left')

In [154]:
orders_with_customers.shape

(99441, 9)

In [155]:
orders_per_unique_customer = (
    orders_with_customers.groupby('customer_unique_id')
    .size()
)

orders_per_unique_customer.head()

customer_unique_id
0000366f3b9a7992bf8c76cfdf3221e2    1
0000b849f77a49e4a4ce2b2a4ca5be3f    1
0000f46a3911fa3c0805444483337064    1
0000f6ccb0745a6a4b88665a16c9f078    1
0004aac84e0df4da2b147fca70cf8255    1
dtype: int64

In [156]:
one_time_customers = (orders_per_unique_customer == 1).sum()

repeat_customers = (orders_per_unique_customer > 1).sum()

one_time_customers, repeat_customers

(np.int64(93099), np.int64(2997))

In [157]:
repeat_customers_rate = (
    repeat_customers / (one_time_customers + repeat_customers)
) * 100

In [158]:
repeat_customers_rate

np.float64(3.1187562437562435)

In [159]:
orders_per_unique_customer.value_counts().sort_index()

1     93099
2      2745
3       203
4        30
5         8
6         6
7         3
9         1
17        1
Name: count, dtype: int64

In [160]:
sellers.isnull().sum()

seller_id                 0
seller_zip_code_prefix    0
seller_city               0
seller_state              0
dtype: int64

In [161]:
sellers.duplicated().sum()

np.int64(0)

In [162]:
(sellers['seller_zip_code_prefix'] < 0).sum()

np.int64(0)

In [163]:
sellers['seller_zip_code_prefix'].astype(str).str.len().value_counts()

seller_zip_code_prefix
5    2068
4    1027
Name: count, dtype: int64

In [164]:
sellers['seller_state'].nunique()

23

In [165]:
sellers['seller_state'].unique()

<StringArray>
['SP', 'RJ', 'PE', 'PR', 'GO', 'SC', 'BA', 'DF', 'RS', 'MG', 'RN', 'MT', 'CE',
 'PB', 'AC', 'ES', 'RO', 'PI', 'MS', 'SE', 'MA', 'AM', 'PA']
Length: 23, dtype: str

In [166]:
(sellers['seller_city'].str.strip() == "").sum()

np.int64(0)

In [167]:
sellers['seller_city'].nunique()

611

In [168]:
sellers['seller_city'].value_counts().head(10)

seller_city
sao paulo         694
curitiba          127
rio de janeiro     96
belo horizonte     68
ribeirao preto     52
guarulhos          50
ibitinga           49
santo andre        45
campinas           41
maringa            40
Name: count, dtype: int64

In [169]:
geolocation.isnull().sum()

geolocation_zip_code_prefix    0
geolocation_lat                0
geolocation_lng                0
geolocation_city               0
geolocation_state              0
dtype: int64

In [170]:
geolocation['geolocation_zip_code_prefix'].nunique()

19015

In [171]:
geolocation['geolocation_zip_code_prefix'].value_counts().head(10)

geolocation_zip_code_prefix
24220    1146
24230    1102
38400     965
35500     907
11680     879
22631     832
30140     810
11740     788
38408     773
28970     743
Name: count, dtype: int64

In [172]:
geolocation['geolocation_lat'].max()

np.float64(45.06593318269697)

In [173]:
geolocation['geolocation_lat'].min()

np.float64(-36.6053744107061)

In [174]:
geolocation['geolocation_lng'].max()

np.float64(121.10539381057764)

In [175]:
geolocation['geolocation_lng'].min()

np.float64(-101.46676644931476)

In [176]:
(geolocation['geolocation_city'].str.strip() == "").sum()

np.int64(0)

In [177]:
(geolocation['geolocation_state'].str.strip()=="").sum()

np.int64(0)

In [178]:
valid_states = {
    "AC", "AL", "AP", "AM", "BA", "CE", "DF",
    "ES", "GO", "MA", "MT", "MS", "MG", "PA",
    "PB", "PR", "PE", "PI", "RJ", "RN", "RS",
    "RO", "RR", "SC", "SP", "SE", "TO"
}

geolocation[
    ~geolocation['geolocation_state'].isin(valid_states)
]["geolocation_state"].unique()

<StringArray>
[]
Length: 0, dtype: str

In [179]:
geolocation['geolocation_city'].nunique()

8011

In [180]:
geolocation['geolocation_city'].value_counts().head(10)

geolocation_city
sao paulo                135800
rio de janeiro            62151
belo horizonte            27805
são paulo                 24918
curitiba                  16593
porto alegre              13521
salvador                  11865
guarulhos                 11340
brasilia                  10470
sao bernardo do campo      8112
Name: count, dtype: int64

In [181]:
(order_items['price'] < 0).sum()

np.int64(0)

In [182]:
(order_items['freight_value'] < 0).sum()

np.int64(0)

In [183]:
(order_items['order_item_id'] < 1).sum()

np.int64(0)

In [184]:
order_items.groupby('order_id').size().max()

np.int64(21)

In [185]:
order_items.duplicated(
    subset=["order_id", "order_item_id"]
).sum()

np.int64(0)

In [186]:
(payments['payment_sequential'] < 1).sum()

np.int64(0)

In [187]:
payments["payment_sequential"].max()

np.int64(29)

In [188]:
payments.groupby("order_id")["payment_sequential"].max().max()

np.int64(29)

In [189]:
payments.loc[
    payments["payment_sequential"] == 29,
    ["order_id", "payment_sequential", "payment_type", "payment_installments", "payment_value"]
]

,order_id,payment_sequential,payment_type,payment_installments,payment_value
39108,fa65dad1b0e818e3ccc5cb0e39231352,29,voucher,1,19.26

In [190]:
payments.loc[
    payments["order_id"] == "fa65dad1b0e818e3ccc5cb0e39231352"
].sort_values("payment_sequential")

,order_id,payment_sequential,payment_type,payment_installments,payment_value
14321,fa65dad1b0e818e3ccc5cb0e39231352,1,voucher,1,3.71
23074,fa65dad1b0e818e3ccc5cb0e39231352,2,voucher,1,8.51
65641,fa65dad1b0e818e3ccc5cb0e39231352,3,voucher,1,2.95
9985,fa65dad1b0e818e3ccc5cb0e39231352,4,voucher,1,29.16
28330,fa65dad1b0e818e3ccc5cb0e39231352,5,voucher,1,0.66
29648,fa65dad1b0e818e3ccc5cb0e39231352,6,voucher,1,5.02
82593,fa65dad1b0e818e3ccc5cb0e39231352,7,voucher,1,0.32
68853,fa65dad1b0e818e3ccc5cb0e39231352,8,voucher,1,26.02
17274,fa65dad1b0e818e3ccc5cb0e39231352,9,voucher,1,1.08
19565,fa65dad1b0e818e3ccc5cb0e39231352,10,voucher,1,12.86
32519,fa65dad1b0e818e3ccc5cb0e39231352,11,voucher,1,4.03
73537,fa65dad1b0e818e3ccc5cb0e39231352,12,voucher,1,3.60
77885,fa65dad1b0e818e3ccc5cb0e39231352,13,voucher,1,0.00
36822,fa65dad1b0e818e3ccc5cb0e39231352,14,voucher,1,0.00
63369,fa65dad1b0e818e3ccc5cb0e39231352,15,voucher,1,14.04
78050,fa65dad1b0e818e3ccc5cb0e39231352,16,voucher,1,12.86
79670,fa65dad1b0e818e3ccc5cb0e39231352,17,voucher,1,3.72
80321,fa65dad1b0e818e3ccc5cb0e39231352,18,voucher,1,0.73
74721,fa65dad1b0e818e3ccc5cb0e39231352,19,voucher,1,5.02
93337,fa65dad1b0e818e3ccc5cb0e39231352,20,voucher,1,150.00
74239,fa65dad1b0e818e3ccc5cb0e39231352,21,voucher,1,4.11
100606,fa65dad1b0e818e3ccc5cb0e39231352,22,voucher,1,4.03
85166,fa65dad1b0e818e3ccc5cb0e39231352,23,voucher,1,18.86
99213,fa65dad1b0e818e3ccc5cb0e39231352,24,voucher,1,0.42
24879,fa65dad1b0e818e3ccc5cb0e39231352,25,voucher,1,3.68
79587,fa65dad1b0e818e3ccc5cb0e39231352,26,voucher,1,28.27
4885,fa65dad1b0e818e3ccc5cb0e39231352,27,voucher,1,66.02
39111,fa65dad1b0e818e3ccc5cb0e39231352,28,voucher,1,29.05
39108,fa65dad1b0e818e3ccc5cb0e39231352,29,voucher,1,19.26

In [191]:
payments.duplicated(
    subset=["order_id", "payment_sequential"]
).sum()

np.int64(0)

In [192]:
reviews_with_order = reviews.merge(
    orders[["order_id", "order_purchase_timestamp"]],
    on="order_id",
    how="left"
)

In [193]:
reviews_with_order.shape

(99224, 8)

In [194]:
reviews_with_order['order_purchase_timestamp'].isnull().sum()

np.int64(0)

In [195]:
review_before_purchase = (
    reviews_with_order["review_creation_date"]
    < reviews_with_order["order_purchase_timestamp"]
)

review_before_purchase.sum()

np.int64(74)

In [196]:
reviews_before_purchase = reviews_with_order.loc[
    review_before_purchase,
    [
        "order_id",
        "order_purchase_timestamp",
        "review_creation_date",
        "review_score"
    ]
]

reviews_before_purchase.head(20)

,order_id,order_purchase_timestamp,review_creation_date,review_score
5293,4d59cc2a2e7bb6c0a851725f5888a9b5,2018-09-06 14:50:07,2018-07-31,5
5503,e5215415bb6f76fe3b7cb68103a0d1c0,2016-10-22 08:25:27,2016-10-09,1
6857,b44b36e6b69be34f58753d3b56d24001,2018-08-08 14:27:00,2018-08-08,1
8404,7813842ae95e8c497fc0233232ae815a,2018-08-17 20:06:36,2018-08-03,1
8486,392ed9afd714e3c74767d0c4d3e3f477,2018-09-29 09:13:03,2018-08-26,1
9020,00b1cb0320190ca0daa2c88b35206009,2018-08-28 15:26:39,2018-08-28,1
10412,0fb9645c128ac84788798f0129496ca7,2018-08-21 10:15:51,2018-08-04,1
10445,2bb02fdf5637a68cd5d13c78c37c3376,2018-08-09 10:55:10,2018-08-01,2
13454,f81e71dd7c044a9ee7c1d6e37d68d64f,2018-08-15 08:34:42,2018-07-21,1
13872,a89abace0dcc01eeb267a9660b5ac126,2018-09-06 18:45:47,2018-07-31,4
18311,b102b42cde7719ae4b7c0163cf4d7dbe,2018-08-29 10:15:27,2018-08-12,3
18897,afed0d88ec7753e7be8744bb66e860d1,2018-08-02 15:23:07,2018-07-28,1
19598,2663ce3526465b7ee9809428adabdc45,2018-08-30 13:07:46,2018-08-23,2
20363,74e198a81e758ec637a42e8f2e856927,2018-08-18 09:27:28,2018-08-18,1
21247,5290c34bd38a8a095b885f13958db1e1,2018-08-21 10:25:18,2018-08-18,3
24192,ebc94658c583ab37ad4f8e9091c4bef2,2018-04-14 08:22:43,2018-03-30,2
24262,82fd1196a459f594fb1d66e667fc74c4,2018-04-10 21:09:18,2018-01-23,4
24897,ec88cd13421e27489ffc1f352247f3a4,2018-08-24 16:38:44,2018-08-24,5
25016,e49e7ce1471b4693482d40c2bd3ad196,2018-08-07 11:16:28,2018-08-04,2
29202,4608a27e9e60c05b054631def491e7af,2018-08-28 08:10:22,2018-08-08,1

In [197]:
reviews_before_purchase = reviews_before_purchase.copy()

reviews_before_purchase["days_difference"] = (
    reviews_before_purchase["order_purchase_timestamp"]
    - reviews_before_purchase["review_creation_date"]
).dt.days

reviews_before_purchase.sort_values(
    "days_difference",
    ascending=False
).head(20)

,order_id,order_purchase_timestamp,review_creation_date,review_score,days_difference
92235,b059ee4de278302d550a3035c4cdb740,2018-10-16 20:16:02,2018-06-27,5,111
82057,0cb763300f5679bee73a0b0fdfe0a2d2,2018-08-10 18:54:48,2018-05-05,5,97
24262,82fd1196a459f594fb1d66e667fc74c4,2018-04-10 21:09:18,2018-01-23,4,77
59696,10a045cdf6a5650c21e9cfeb60384c16,2018-10-17 17:30:18,2018-08-23,1,55
66680,ed3efbd3a87bea76c2812c66a0b32219,2018-09-20 13:54:16,2018-07-28,2,54
92768,a2ac6dad85cf8af5b0afb510a240fe8c,2018-10-03 18:55:29,2018-08-18,1,46
44025,5aac76cf7b07dd06fa4d50bf461d2f40,2018-09-25 11:59:18,2018-08-14,1,42
36453,af07804a2d53e8639954baf97fbf803a,2018-04-19 13:46:42,2018-03-10,1,40
37168,616fa7d4871b87832197b2a137a115d2,2018-10-01 15:30:09,2018-08-23,2,39
65292,3a3cddda5a7c27851bd96c3313412840,2018-08-31 16:13:44,2018-07-24,5,38
13872,a89abace0dcc01eeb267a9660b5ac126,2018-09-06 18:45:47,2018-07-31,4,37
5293,4d59cc2a2e7bb6c0a851725f5888a9b5,2018-09-06 14:50:07,2018-07-31,5,37
56320,4bb9c2002502ca416276dc1ff5efb1b3,2018-06-23 14:53:03,2018-05-18,1,36
87866,ea844c92cf978ea23321fa7fe5871761,2018-09-13 09:56:12,2018-08-09,1,35
81056,a805d7a514bcde0719f99ddf2a3bb31d,2018-08-17 14:17:56,2018-07-14,1,34
8486,392ed9afd714e3c74767d0c4d3e3f477,2018-09-29 09:13:03,2018-08-26,1,34
36302,572c4bbf0f5f85a9b4a2c4fe0c7f04d5,2018-08-30 15:11:58,2018-07-31,5,30
86358,0623dbbd06c0d4059dbfefab8748a491,2018-08-20 14:17:09,2018-07-25,1,26
45176,869997fbe01f39d184956b5c6bccfdbe,2018-09-26 08:40:15,2018-08-31,1,26
83855,27667a063cb59b5d987a5a71c192cce5,2018-08-27 19:54:54,2018-08-02,1,25

In [198]:
review_answer_before_creation = (
    reviews["review_answer_timestamp"]
    < reviews["review_creation_date"]
)

review_answer_before_creation.sum()

np.int64(0)

In [199]:
orders['order_id'].isin(reviews['order_id']).eq(False).sum()

np.int64(768)

In [200]:
review_coverage = (
    orders['order_id'].isin(reviews['order_id']).mean()
)*100

review_coverage

np.float64(99.22768274655324)

In [201]:
sellers.isnull().sum()

seller_id                 0
seller_zip_code_prefix    0
seller_city               0
seller_state              0
dtype: int64

In [202]:
sellers['seller_id'].duplicated().sum()

np.int64(0)

In [203]:
(sellers["seller_zip_code_prefix"] < 0).sum()

np.int64(0)

In [204]:
sellers['seller_zip_code_prefix'].astype(str).str.len().value_counts()

seller_zip_code_prefix
5    2068
4    1027
Name: count, dtype: int64

In [205]:
valid_states = {
    "AC", "AL", "AP", "AM", "BA", "CE", "DF",
    "ES", "GO", "MA", "MT", "MS", "MG", "PA",
    "PB", "PR", "PE", "PI", "RJ", "RN", "RS",
    "RO", "RR", "SC", "SP", "SE", "TO"
}

sellers[
    ~sellers["seller_state"].isin(valid_states)
]["seller_state"].unique()

<StringArray>
[]
Length: 0, dtype: str

In [206]:
(sellers['seller_city'].str.strip() == "").sum()

np.int64(0)

In [207]:
category_translation.isnull().sum()

product_category_name            0
product_category_name_english    0
dtype: int64

In [208]:
category_translation['product_category_name'].duplicated().sum()

np.int64(0)

In [209]:
category_translation['product_category_name_english'].duplicated().sum()

np.int64(0)

In [210]:
untranslated_categories = products.loc[
    products["product_category_name"].notna()
    & ~products["product_category_name"].isin(
        category_translation["product_category_name"]
    ),
    "product_category_name"
]

untranslated_categories.value_counts()

product_category_name
portateis_cozinha_e_preparadores_de_alimentos    10
pc_gamer                                          3
Name: count, dtype: int64

In [211]:
unused_translations = category_translation.loc[
    ~category_translation["product_category_name"].isin(
        products["product_category_name"]
    ),
    "product_category_name"
]

unused_translations

Series([], Name: product_category_name, dtype: str)

In [212]:
geolocation.isnull().sum()

geolocation_zip_code_prefix    0
geolocation_lat                0
geolocation_lng                0
geolocation_city               0
geolocation_state              0
dtype: int64

In [213]:
(
    (geolocation["geolocation_lat"] < -90)
    | (geolocation["geolocation_lat"] > 90)
).sum()

np.int64(0)

In [214]:
(
    (geolocation["geolocation_lng"] < -180)
    | (geolocation["geolocation_lng"] > 180)
).sum()

np.int64(0)

In [215]:
(geolocation["geolocation_zip_code_prefix"] < 0).sum()

np.int64(0)

In [216]:
geolocation["geolocation_zip_code_prefix"].nunique()

19015

In [217]:
geolocation["geolocation_zip_code_prefix"].value_counts().head(10)

geolocation_zip_code_prefix
24220    1146
24230    1102
38400     965
35500     907
11680     879
22631     832
30140     810
11740     788
38408     773
28970     743
Name: count, dtype: int64

In [218]:
geolocation[
    ~geolocation["geolocation_state"].isin(valid_states)
]["geolocation_state"].unique()

<StringArray>
[]
Length: 0, dtype: str

In [219]:
(geolocation["geolocation_city"].str.strip() == "").sum()

np.int64(0)

In [220]:
items_per_order = order_items.groupby("order_id").size()

orders_without_items = (
    ~orders["order_id"].isin(items_per_order.index)
).sum()

orders_without_items

np.int64(775)

In [221]:
orders_without_items = orders.loc[
    ~orders["order_id"].isin(items_per_order.index)
]

orders_without_items["order_status"].value_counts()

order_status
unavailable    603
canceled       164
created          5
invoiced         2
shipped          1
Name: count, dtype: int64

In [222]:
item_order_ids = order_items["order_id"].unique()

items_without_payment = (
    ~pd.Series(item_order_ids).isin(payments["order_id"])
).sum()

items_without_payment

np.int64(1)

In [223]:
orders_without_payment = orders.loc[
    ~orders["order_id"].isin(payments["order_id"])
]

orders_without_payment

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
30710,bfbd0f9bdef84302105ad712db648a6c,86dc2ffce2dfff336de2f386a786e574,delivered,2016-09-15 12:16:38,2016-09-15 12:16:38,2016-11-07 17:11:53,2016-11-09 07:47:38,2016-10-04

In [224]:
orders_without_payment_items = order_items.loc[
    order_items["order_id"] == "bfbd0f9bdef84302105ad712db648a6c"
]

orders_without_payment_items

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
84389,bfbd0f9bdef84302105ad712db648a6c,1,5a6b04657a4c5ee34285d1e4619a96b4,ecccfa2bb93b34a3bf033cc5d1dcdc69,2016-09-19 23:11:33,44.99,2.83
84390,bfbd0f9bdef84302105ad712db648a6c,2,5a6b04657a4c5ee34285d1e4619a96b4,ecccfa2bb93b34a3bf033cc5d1dcdc69,2016-09-19 23:11:33,44.99,2.83
84391,bfbd0f9bdef84302105ad712db648a6c,3,5a6b04657a4c5ee34285d1e4619a96b4,ecccfa2bb93b34a3bf033cc5d1dcdc69,2016-09-19 23:11:33,44.99,2.83