In [1]:
import pandas as pd

orders = pd.read_csv("../data/olist_orders_dataset.csv")
customers = pd.read_csv("../data/olist_customers_dataset.csv")
order_items = pd.read_csv("../data/olist_order_items_dataset.csv")
products = pd.read_csv("../data/olist_products_dataset.csv")
sellers = pd.read_csv("../data/olist_sellers_dataset.csv")
payments = pd.read_csv("../data/olist_order_payments_dataset.csv")
reviews = pd.read_csv("../data/olist_order_reviews_dataset.csv")
category_translation = pd.read_csv("../data/product_category_name_translation.csv")
geolocation = pd.read_csv("../data/olist_geolocation_dataset.csv")

In [2]:
print("orders:", orders.shape)
print("customers:", customers.shape)
print("order_items:", order_items.shape)
print("products:", products.shape)
print("sellers:", sellers.shape)
print("payments:", payments.shape)
print("reviews:", reviews.shape)
print("category_translation:", category_translation.shape)
print("geolocation:", geolocation.shape)

orders: (99441, 8)
customers: (99441, 5)
order_items: (112650, 7)
products: (32951, 9)
sellers: (3095, 4)
payments: (103886, 5)
reviews: (99224, 7)
category_translation: (71, 2)
geolocation: (1000163, 5)

In [3]:
date_cols = [
    "order_purchase_timestamp",
    "order_approved_at",
    "order_delivered_carrier_date",
    "order_delivered_customer_date",
    "order_estimated_delivery_date"
]

orders[date_cols] = orders[date_cols].apply(pd.to_datetime)

In [4]:
orders.dtypes

order_id                                    str
customer_id                                 str
order_status                                str
order_purchase_timestamp         datetime64[us]
order_approved_at                datetime64[us]
order_delivered_carrier_date     datetime64[us]
order_delivered_customer_date    datetime64[us]
order_estimated_delivery_date    datetime64[us]
dtype: object

In [5]:
customers['customer_zip_code_prefix'] = customers['customer_zip_code_prefix'].astype(str).str.zfill(5)

In [6]:
customers['customer_zip_code_prefix'].head(10)

0    14409
1    09790
2    01151
3    08775
4    13056
5    89254
6    04534
7    35182
8    81560
9    30575
Name: customer_zip_code_prefix, dtype: str

In [7]:
customers['customer_zip_code_prefix'].str.len().value_counts()

customer_zip_code_prefix
5    99441
Name: count, dtype: int64

In [8]:
sellers['seller_zip_code_prefix'] = sellers['seller_zip_code_prefix'].astype(str).str.zfill(5)

In [9]:
sellers['seller_zip_code_prefix'].head(10)

0    13023
1    13844
2    20031
3    04195
4    12914
5    20920
6    55325
7    16304
8    01529
9    80310
Name: seller_zip_code_prefix, dtype: str

In [10]:
sellers['seller_zip_code_prefix'].str.len().value_counts()

seller_zip_code_prefix
5    3095
Name: count, dtype: int64

In [11]:
geolocation['geolocation_zip_code_prefix'] = geolocation['geolocation_zip_code_prefix'].astype(str).str.zfill(5)

In [12]:
geolocation['geolocation_zip_code_prefix'].head(10)

0    01037
1    01046
2    01046
3    01041
4    01035
5    01012
6    01047
7    01013
8    01029
9    01011
Name: geolocation_zip_code_prefix, dtype: str

In [13]:
geolocation['geolocation_zip_code_prefix'].str.len().value_counts()

geolocation_zip_code_prefix
5    1000163
Name: count, dtype: int64

In [14]:
customers['customer_city'] = customers['customer_city'].str.strip()
customers['customer_state'] = customers['customer_state'].str.strip()

In [15]:
sellers['seller_city'] = sellers['seller_city'].str.strip()
sellers['seller_state'] = sellers['seller_state'].str.strip()

In [16]:
print("city", (sellers['seller_city'] == " ").sum())
print("state", (sellers['seller_state'] == " ").sum())

city 0
state 0

In [17]:
geolocation['geolocation_city'] = geolocation['geolocation_city'].str.strip()
geolocation['geolocation_state'] = geolocation['geolocation_state'].str.strip()

In [18]:
print("city",(geolocation['geolocation_city'] == " ").sum())
print("state",(geolocation['geolocation_state'] == " ").sum())

city 0
state 0

In [19]:
products['product_category_name'].isna().sum()

np.int64(610)

In [20]:
products['product_category_name'] = products['product_category_name'].fillna("Unknown")

In [21]:
products['product_category_name'].isna().sum()

np.int64(0)

In [22]:
products["product_category_name"] = products["product_category_name"].replace(
    "Unkonwn",
    "Unknown"
)

In [23]:
(products["product_category_name"] == "unkonwn").sum()

np.int64(0)

In [24]:
products["product_category_name"].value_counts().loc["Unknown"]

np.int64(610)

In [25]:
products[[
    "product_weight_g",
    "product_length_cm",
    "product_height_cm",
    "product_width_cm"
]].isna().sum()

product_weight_g     2
product_length_cm    2
product_height_cm    2
product_width_cm     2
dtype: int64

In [27]:
measurement_cols = [
    "product_weight_g",
    "product_length_cm",
    "product_height_cm",
    "product_width_cm"
]

products[products[measurement_cols].isna().any(axis=1)]

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
8578,09ff539a621711667c43eba6a3bd8466,bebes,60.0,865.0,3.0,NaN,NaN,NaN,NaN
18851,5eb564652db742ff8f28759cd8d2652a,Unknown,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [28]:
description_cols = [
    "product_name_lenght",
    "product_description_lenght",
    "product_photos_qty"
]

products[products[description_cols].isna().all(axis=1)]

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
105,a41e356c76fab66334f36de622ecbd3a,Unknown,NaN,NaN,NaN,650.0,17.0,14.0,12.0
128,d8dee61c2034d6d075997acef1870e9b,Unknown,NaN,NaN,NaN,300.0,16.0,7.0,20.0
145,56139431d72cd51f19eb9f7dae4d1617,Unknown,NaN,NaN,NaN,200.0,20.0,20.0,20.0
154,46b48281eb6d663ced748f324108c733,Unknown,NaN,NaN,NaN,18500.0,41.0,30.0,41.0
197,5fb61f482620cb672f5e586bb132eae9,Unknown,NaN,NaN,NaN,300.0,35.0,7.0,12.0
...,...,...,...,...,...,...,...,...,...
32515,b0a0c5dd78e644373b199380612c350a,Unknown,NaN,NaN,NaN,1800.0,30.0,20.0,70.0
32589,10dbe0fbaa2c505123c17fdc34a63c56,Unknown,NaN,NaN,NaN,800.0,30.0,10.0,23.0
32616,bd2ada37b58ae94cc838b9c0569fecd8,Unknown,NaN,NaN,NaN,200.0,21.0,8.0,16.0
32772,fa51e914046aab32764c41356b9d4ea4,Unknown,NaN,NaN,NaN,1300.0,45.0,16.0,45.0
32852,c4ceee876c82b8328e9c293fa0e1989b,Unknown,NaN,NaN,NaN,700.0,28.0,3.0,43.0

In [29]:
products.isna().sum()

product_id                      0
product_category_name           0
product_name_lenght           610
product_description_lenght    610
product_photos_qty            610
product_weight_g                2
product_length_cm               2
product_height_cm               2
product_width_cm                2
dtype: int64

In [30]:
products = products.rename(columns={
    "product_name_lenght": "product_name_length",
    "product_description_lenght": "product_description_length"
})

In [31]:
products.columns

Index(['product_id', 'product_category_name', 'product_name_length',
       'product_description_length', 'product_photos_qty', 'product_weight_g',
       'product_length_cm', 'product_height_cm', 'product_width_cm'],
      dtype='str')

In [32]:
numeric_product_cols = [
    "product_name_length",
    "product_description_length",
    "product_photos_qty",
    "product_weight_g",
    "product_length_cm",
    "product_height_cm",
    "product_width_cm"
]

(products[numeric_product_cols] < 0).sum()

product_name_length           0
product_description_length    0
product_photos_qty            0
product_weight_g              0
product_length_cm             0
product_height_cm             0
product_width_cm              0
dtype: int64

In [33]:
whole_number_cols = [
    "product_name_length",
    "product_description_length",
    "product_photos_qty"
]

(products[whole_number_cols] % 1 != 0).sum()

product_name_length           610
product_description_length    610
product_photos_qty            610
dtype: int64

In [34]:
(products[whole_number_cols].dropna() % 1 != 0).sum()

product_name_length           0
product_description_length    0
product_photos_qty            0
dtype: int64

In [35]:
sellers.isna().sum()

seller_id                 0
seller_zip_code_prefix    0
seller_city               0
seller_state              0
dtype: int64

In [36]:
sellers['seller_id'].duplicated().sum()

np.int64(0)

In [37]:
sellers["seller_zip_code_prefix"].str.len().value_counts()

seller_zip_code_prefix
5    3095
Name: count, dtype: int64

In [38]:
valid_states = {
    "AC", "AL", "AP", "AM", "BA", "CE", "DF",
    "ES", "GO", "MA", "MT", "MS", "MG", "PA",
    "PB", "PR", "PE", "PI", "RJ", "RN", "RS",
    "RO", "RR", "SC", "SP", "SE", "TO"
}

sellers[~sellers["seller_state"].isin(valid_states)]["seller_state"].unique()

<StringArray>
[]
Length: 0, dtype: str

In [39]:
sellers.dtypes

seller_id                 str
seller_zip_code_prefix    str
seller_city               str
seller_state              str
dtype: object

In [40]:
payments.isna().sum()

order_id                0
payment_sequential      0
payment_type            0
payment_installments    0
payment_value           0
dtype: int64

In [41]:
payments.duplicated(
    subset=["order_id", "payment_sequential"]
).sum()

np.int64(0)

In [42]:
payments.dtypes

order_id                    str
payment_sequential        int64
payment_type                str
payment_installments      int64
payment_value           float64
dtype: object

In [43]:
(payments[["payment_installments",
    "payment_value"]] < 0).sum()

payment_installments    0
payment_value           0
dtype: int64

In [44]:
payments[payments['payment_installments'] == 0]

,order_id,payment_sequential,payment_type,payment_installments,payment_value
46982,744bade1fcf9ff3f31d860ace076d422,2,credit_card,0,58.69
79014,1a57108394169c0b47d8f876acc9ba2d,2,credit_card,0,129.94

In [45]:
payments[payments['payment_value'] == 0]

,order_id,payment_sequential,payment_type,payment_installments,payment_value
19922,8bcbe01d44d147f901cd3192671144db,4,voucher,1,0.0
36822,fa65dad1b0e818e3ccc5cb0e39231352,14,voucher,1,0.0
43744,6ccb433e00daae1283ccc956189c82ae,4,voucher,1,0.0
51280,4637ca194b6387e2d538dc89b124b0ee,1,not_defined,1,0.0
57411,00b1cb0320190ca0daa2c88b35206009,1,not_defined,1,0.0
62674,45ed6e85398a87c253db47c2d9f48216,3,voucher,1,0.0
77885,fa65dad1b0e818e3ccc5cb0e39231352,13,voucher,1,0.0
94427,c8c528189310eaa44a745b8d9d26908b,1,not_defined,1,0.0
100766,b23878b3e8eb4d25a158f57d96331b18,4,voucher,1,0.0

In [46]:
payments['payment_type'].unique()

<StringArray>
['credit_card', 'boleto', 'voucher', 'debit_card', 'not_defined']
Length: 5, dtype: str

In [47]:
reviews.isna().sum()

review_id                      0
order_id                       0
review_score                   0
review_comment_title       87656
review_comment_message     58247
review_creation_date           0
review_answer_timestamp        0
dtype: int64

In [48]:
reviews['review_score'].value_counts().sort_index()

review_score
1    11424
2     3151
3     8179
4    19142
5    57328
Name: count, dtype: int64

In [49]:
reviews['review_id'].duplicated().sum()

np.int64(814)

In [50]:
reviews[reviews["review_id"].duplicated(keep=False)].sort_values("review_id").head(20)

,review_id,order_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp
46678,00130cbe1f9d422698c812ed8ded1919,dfcdfc43867d1c1381bfaf62d6b9c195,1,NaN,"O cartucho ""original HP"" 60XL não é reconhecid...",2018-03-07 00:00:00,2018-03-20 18:08:23
29841,00130cbe1f9d422698c812ed8ded1919,04a28263e085d399c97ae49e0b477efa,1,NaN,"O cartucho ""original HP"" 60XL não é reconhecid...",2018-03-07 00:00:00,2018-03-20 18:08:23
90677,0115633a9c298b6a98bcbe4eee75345f,78a4201f58af3463bdab842eea4bc801,5,NaN,NaN,2017-09-21 00:00:00,2017-09-26 03:27:47
63193,0115633a9c298b6a98bcbe4eee75345f,0c9850b2c179c1ef60d2855e2751d1fa,5,NaN,NaN,2017-09-21 00:00:00,2017-09-26 03:27:47
92876,0174caf0ee5964646040cd94e15ac95e,f93a732712407c02dce5dd5088d0f47b,1,NaN,Produto entregue dentro de embalagem do fornec...,2018-03-07 00:00:00,2018-03-08 03:00:53
57280,0174caf0ee5964646040cd94e15ac95e,74db91e33b4e1fd865356c89a61abf1f,1,NaN,Produto entregue dentro de embalagem do fornec...,2018-03-07 00:00:00,2018-03-08 03:00:53
54832,017808d29fd1f942d97e50184dfb4c13,8daaa9e99d60fbba579cc1c3e3bfae01,5,NaN,NaN,2018-03-02 00:00:00,2018-03-05 01:43:30
99167,017808d29fd1f942d97e50184dfb4c13,b1461c8882153b5fe68307c46a506e39,5,NaN,NaN,2018-03-02 00:00:00,2018-03-05 01:43:30
20621,0254bd905dc677a6078990aad3331a36,5bf226cf882c5bf4247f89a97c86f273,1,NaN,O pedido consta de 2 produtos e até agora rece...,2017-09-09 00:00:00,2017-09-13 09:52:44
96080,0254bd905dc677a6078990aad3331a36,331b367bdd766f3d1cf518777317b5d9,1,NaN,O pedido consta de 2 produtos e até agora rece...,2017-09-09 00:00:00,2017-09-13 09:52:44
89712,0288d42bef3dfe36930740c9588a570f,33d8795f04dd631f3480d7aaf90da3dc,3,NaN,NaN,2017-07-29 00:00:00,2017-07-31 17:11:04
94851,0288d42bef3dfe36930740c9588a570f,f889a5a0b44adc29c5465b99395ac3c1,3,NaN,NaN,2017-07-29 00:00:00,2017-07-31 17:11:04
47495,02aa7f5f75e964e3c7efa59a1f515281,d8e17d5f7dacf0970d316e7c03e741e8,3,NaN,NaN,2017-07-27 00:00:00,2017-07-29 15:09:50
95860,02aa7f5f75e964e3c7efa59a1f515281,db92613c074f00e53066388d48ad7512,3,NaN,NaN,2017-07-27 00:00:00,2017-07-29 15:09:50
71165,034528cb00b6bc981847acafbdf2ae0b,e1e8e3bca903de27e9a1c72b5a5795e0,1,NaN,NaN,2017-05-14 00:00:00,2017-05-15 02:17:38
81094,034528cb00b6bc981847acafbdf2ae0b,3d3742a96f24a8fe4e2e57628807e476,1,NaN,NaN,2017-05-14 00:00:00,2017-05-15 02:17:38
1988,03a6a25db577d0689440933055111897,2acfdc5131ff2cf4433e668454c9784c,5,NaN,Muito Bom! Gostei Bastante! Tecido Ótimo! Aten...,2017-12-15 00:00:00,2017-12-16 01:32:18
9013,03a6a25db577d0689440933055111897,3fde8b7313af6b37b84b5c7594d7add0,5,NaN,Muito Bom! Gostei Bastante! Tecido Ótimo! Aten...,2017-12-15 00:00:00,2017-12-16 01:32:18
21587,0467560f511c516ddaa54a60edb0c291,0c995611a99f81268d859184a416f1db,5,NaN,NaN,2017-02-09 00:00:00,2017-02-14 15:58:44
24901,0467560f511c516ddaa54a60edb0c291,55b2e390d5d80ada31ad1b795ebeb087,5,NaN,NaN,2017-02-09 00:00:00,2017-02-14 15:58:44

In [51]:
review_id_order_counts = (
    reviews
    .groupby("review_id")["order_id"]
    .nunique()
)

review_id_order_counts.value_counts().sort_index()

order_id
1    97621
2      764
3       25
Name: count, dtype: int64

In [52]:
invalid_approval = orders[
    orders["order_approved_at"] < orders["order_purchase_timestamp"]
]

invalid_approval.shape[0]

0

In [54]:
invalid_carrier = orders[
    orders["order_delivered_carrier_date"] < orders["order_approved_at"]
]

invalid_carrier.shape[0]

1359

In [55]:
orders.loc[
    orders["order_delivered_carrier_date"] < orders["order_approved_at"],
    [
        "order_id",
        "order_purchase_timestamp",
        "order_approved_at",
        "order_delivered_carrier_date",
        "order_delivered_customer_date"
    ]
].head(10)

,order_id,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date
15,dcb36b511fcac050b97cd5c05de84dc3,2018-06-07 19:03:12,2018-06-12 23:31:02,2018-06-11 14:54:00,2018-06-21 15:34:32
64,688052146432ef8253587b930b01a06d,2018-04-22 08:48:13,2018-04-24 18:25:22,2018-04-23 19:19:14,2018-04-24 19:31:58
199,58d4c4747ee059eeeb865b349b41f53a,2018-07-21 12:49:32,2018-07-26 23:31:53,2018-07-24 12:57:00,2018-07-25 23:58:19
210,412fccb2b44a99b36714bca3fef8ad7b,2018-07-22 22:30:05,2018-07-23 12:31:53,2018-07-23 12:24:00,2018-07-24 19:26:42
415,56a4ac10a4a8f2ba7693523bb439eede,2018-07-22 13:04:47,2018-07-27 23:31:09,2018-07-24 14:03:00,2018-07-28 00:05:39
481,32e4fa9bb468884309b58b9348de70c3,2018-07-04 16:49:21,2018-07-05 16:33:06,2018-07-05 14:50:00,2018-07-07 14:41:18
483,4df92d82d79c3b52c7138679fa9b07fc,2018-07-24 11:32:11,2018-07-29 23:30:52,2018-07-26 14:46:00,2018-07-27 18:55:57
585,16e38caa92e342c7780f68832f832d4d,2018-05-07 01:09:09,2018-05-07 16:52:39,2018-05-07 15:09:00,2018-05-24 00:31:18
615,b9afddbdcfadc9a87b41a83271c3e888,2018-08-16 13:50:48,2018-08-16 14:05:13,2018-08-16 13:27:00,2018-08-24 14:58:37
817,6051e6d3da9a50b7325cbe9c81025062,2018-07-03 23:40:16,2018-07-05 16:31:26,2018-07-04 12:14:00,2018-07-05 22:52:28

In [56]:
invalid_delivery = orders[
    orders["order_delivered_customer_date"]
    < orders["order_delivered_carrier_date"]
]

invalid_delivery.shape[0]

23

In [57]:
orders.loc[
    orders["order_delivered_customer_date"]
    < orders["order_delivered_carrier_date"],
    [
        "order_id",
        "order_purchase_timestamp",
        "order_approved_at",
        "order_delivered_carrier_date",
        "order_delivered_customer_date",
        "order_estimated_delivery_date"
    ]
]

,order_id,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
6437,a1abeb653a4d4cd1e142ccb8c82cd069,2017-07-20 11:20:52,2017-07-21 06:43:14,2017-07-28 16:57:58,2017-07-25 19:32:56,2017-08-14
9553,383aa8b2724fe452d9ccd9934a8c628b,2017-07-02 20:58:43,2017-07-02 21:10:20,2017-07-07 17:22:41,2017-07-06 14:27:51,2017-07-21
13487,cb1134f9010d242e9515ad1c78ec0c39,2017-07-16 12:35:34,2017-07-18 06:03:50,2017-07-20 19:22:02,2017-07-19 14:13:28,2017-08-08
14474,dceb62e8fa94b46006c9554fed743df0,2017-07-20 20:58:05,2017-07-22 11:45:11,2017-08-01 18:23:30,2017-07-26 18:09:10,2017-08-11
19268,5f9d46795c3126674e52becb3a1a517f,2017-07-18 11:48:20,2017-07-18 12:03:29,2017-07-20 23:03:42,2017-07-20 18:52:41,2017-07-31
21338,8c78d01de3a9009e23d6877a7cc9be20,2016-10-08 15:36:50,2016-10-08 18:13:44,2016-10-26 11:41:53,2016-10-25 17:51:46,2016-11-30
22520,b27af682321527a6349f1761eb3f360c,2017-06-14 20:17:04,2017-06-14 20:30:08,2017-06-27 14:51:54,2017-06-26 15:45:35,2017-07-14
25393,1cc3ae63caffff2d6c3ee3e78e074acf,2017-08-07 21:35:22,2017-08-08 21:45:15,2017-08-10 18:28:56,2017-08-10 18:05:38,2017-08-25
25646,e37f11cae9985ca58f0b56f268720537,2017-07-26 11:46:34,2017-07-27 10:10:16,2017-08-01 18:17:47,2017-07-31 17:49:56,2017-08-24
27470,fa3e37584f4fdb1ded0e0de700dfcb4e,2017-07-30 19:32:23,2017-07-30 19:45:09,2017-08-09 18:18:43,2017-08-01 21:13:01,2017-08-18
34939,c1e2bf2b7dd3309f2f5356c6b63968fa,2017-02-10 10:19:10,2017-02-10 10:30:13,2017-03-02 17:34:26,2017-02-14 15:15:57,2017-03-15
41636,b866af202be0692766081310cd4085e1,2017-01-27 14:59:17,2017-01-27 15:30:46,2017-02-20 02:32:08,2017-02-15 03:53:46,2017-04-17
45302,29941903985f944b0ffc49c479c1547d,2017-05-29 16:16:50,2017-05-29 16:25:16,2017-06-09 15:07:29,2017-06-02 11:09:16,2017-06-23
49933,76458889992169d3135b264dc13aec67,2016-10-07 10:05:16,2016-10-07 11:24:43,2016-10-26 11:43:06,2016-10-20 18:03:17,2016-11-29
50373,0922ee1619de7b995648e5a8407afb91,2017-07-11 10:45:44,2017-07-11 10:55:15,2017-07-14 12:41:34,2017-07-12 20:49:42,2017-08-14
58428,fbffbaaa30f4077e87ec6acdb835b278,2017-07-30 17:58:26,2017-07-31 07:05:07,2017-08-04 20:04:17,2017-08-03 20:30:00,2017-08-18
68312,3ee6694bb99d5a6db0deceffcd099597,2017-07-07 11:22:13,2017-07-07 12:25:07,2017-07-11 18:15:40,2017-07-11 17:41:26,2017-07-20
71227,19feb5627c41ea1b36a8e50a469b3644,2016-10-07 17:09:56,2016-10-07 17:32:09,2016-10-26 11:42:05,2016-10-20 19:07:54,2016-12-01
74967,d5558a097766363b8e76b38c43332e8a,2017-02-04 19:01:33,2017-02-04 19:31:12,2017-02-15 08:55:26,2017-02-10 07:58:32,2017-03-01
76120,771c4f1f521f462e4b95619e648aaeab,2017-03-22 20:15:15,2017-03-22 20:15:15,2017-03-30 13:14:34,2017-03-28 17:28:32,2017-04-12
78556,ea1dcb4757a844d2642547797bd5feb0,2017-07-18 13:38:29,2017-07-18 13:50:23,2017-07-27 19:21:31,2017-07-25 19:43:10,2017-08-15
90373,99ad48402644a3968f2481defdc57947,2017-08-07 16:36:51,2017-08-07 17:20:06,2017-08-12 00:03:35,2017-08-10 21:22:31,2017-09-05
95634,f688669f48063536e082bb32d634cd46,2016-10-07 10:28:56,2016-10-11 04:56:13,2016-10-21 18:02:40,2016-10-20 20:33:27,2016-11-29

In [58]:
late_deliveries = orders[
    orders["order_delivered_customer_date"]
    > orders["order_estimated_delivery_date"]
]

late_deliveries.shape[0]

7827

In [59]:
invalid_estimate = orders[
    orders["order_estimated_delivery_date"]
    < orders["order_purchase_timestamp"]
]

invalid_estimate.shape[0]

0

In [61]:
payment_counts = payments.groupby("order_id").size()

payment_counts.value_counts().sort_index()

1     96479
2      2382
3       301
4       108
5        52
6        36
7        28
8        11
9         9
10        5
11        8
12        8
13        3
14        2
15        2
19        2
21        1
22        1
26        1
29        1
Name: count, dtype: int64

In [62]:
item_counts = order_items.groupby("order_id").size()

item_counts.value_counts().sort_index()

1     88863
2      7516
3      1322
4       505
5       204
6       198
7        22
8         8
9         3
10        8
11        4
12        5
13        1
14        2
15        2
20        2
21        1
Name: count, dtype: int64

In [63]:
id="9m8zq2"
orders_without_items = ~orders["order_id"].isin(order_items["order_id"])

orders_without_payments = ~orders["order_id"].isin(payments["order_id"])

orders[
    orders_without_items & orders_without_payments
].shape[0]

0

In [64]:
cleaned_shapes = {
    "orders": orders.shape,
    "customers": customers.shape,
    "order_items": order_items.shape,
    "products": products.shape,
    "sellers": sellers.shape,
    "payments": payments.shape,
    "reviews": reviews.shape,
    "category_translation": category_translation.shape,
    "geolocation": geolocation.shape
}

cleaned_shapes

{'orders': (99441, 8),
 'customers': (99441, 5),
 'order_items': (112650, 7),
 'products': (32951, 9),
 'sellers': (3095, 4),
 'payments': (103886, 5),
 'reviews': (99224, 7),
 'category_translation': (71, 2),
 'geolocation': (1000163, 5)}

In [65]:
import os

os.makedirs("../cleaned_data", exist_ok=True)

In [66]:
os.listdir("..")

['.vscode',
 'cleaned_data',
 'dashboard',
 'data',
 'notebook',
 'README.md',
 'sql']

In [67]:
orders.to_csv("../cleaned_data/orders_cleaned.csv", index=False)

In [68]:
os.listdir("../cleaned_data")

['orders_cleaned.csv']

In [69]:
orders_check = pd.read_csv("../cleaned_data/orders_cleaned.csv")

In [70]:
orders_check.shape

(99441, 8)

In [71]:
orders_check.dtypes

order_id                         str
customer_id                      str
order_status                     str
order_purchase_timestamp         str
order_approved_at                str
order_delivered_carrier_date     str
order_delivered_customer_date    str
order_estimated_delivery_date    str
dtype: object

In [72]:
cleaned_tables = {
    "customers": customers,
    "order_items": order_items,
    "products": products,
    "sellers": sellers,
    "payments": payments,
    "reviews": reviews,
    "category_translation": category_translation,
    "geolocation": geolocation
}

for name, df in cleaned_tables.items():
    df.to_csv(f"../cleaned_data/{name}_cleaned.csv", index=False)

In [73]:
os.listdir("../cleaned_data")

['category_translation_cleaned.csv',
 'customers_cleaned.csv',
 'geolocation_cleaned.csv',
 'orders_cleaned.csv',
 'order_items_cleaned.csv',
 'payments_cleaned.csv',
 'products_cleaned.csv',
 'reviews_cleaned.csv',
 'sellers_cleaned.csv']